// <auto-generated />
using System;
using ChatbotAi.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatbotAi.Core.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ChatbotAi.Core.Data.Model.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFromUser")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentMessageId");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("ChatbotAi.Core.Data.Model.ChatMessage", b =>
                {
                    b.HasOne("ChatbotAi.Core.Data.Model.ChatMessage", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMessage");
                });

            modelBuilder.Entity("ChatbotAi.Core.Data.Model.ChatMessage", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
